import sqlite3
import pandas as pd
import google.generativeai as genai

# --- CONFIGURATION ---
# 1. PASTE YOUR API KEY HERE
GOOGLE_API_KEY = "AIzaSyDfuc9zm-cqqksYD6AOPZXKAqyI4fiRgG0" 

# Configure Gemini
genai.configure(api_key=GOOGLE_API_KEY)

def get_gemini_response(question):
    """
    Sends your question + the database schema to Gemini.
    Returns SQL if valid, or 'NO_SQL' if the question is off-topic.
    """
    prompt = [
        """
        You are an expert SQL Assistant for a Flipkart Sales Database.
        
        Here is the Database Schema:
        1. TABLE products (product_id, name, category, price, stock_quantity)
        2. TABLE customers (customer_id, name, city, email, signup_date)
        3. TABLE sales (sale_id, customer_id, product_id, quantity, total_amount, sale_date)
        
        STRICT RULES:
        1. You must ONLY answer questions related to sales, products, customers, and revenue.
        2. If the user asks about anything else (e.g., "Write a poem", "Who is the PM of India", "Python code"), 
           you must return ONLY the text: "NO_SQL".
        3. Do not provide explanations. Return ONLY the SQL code or the word "NO_SQL".
        4. Do not include markdown (no ```sql).
        """
    ]
    
    # Use the model that worked for you
    model = genai.GenerativeModel('gemini-flash-latest')
    response = model.generate_content([prompt[0], question])
    return response.text.strip().replace("```sql", "").replace("```", "")

def execute_query(sql_query):
    """
    Runs the SQL generated by Gemini on your database.
    """
    conn = sqlite3.connect('database.db')
    try:
        # Safety Check: Prevent deletion
        if "DROP" in sql_query.upper() or "DELETE" in sql_query.upper():
            return "SAFETY ALERT: I cannot delete data!"
            
        df = pd.read_sql_query(sql_query, conn)
        return df
    except Exception as e:
        return f"SQL Error: {e}"
    finally:
        conn.close()

# --- MAIN LOOP ---
if __name__ == "__main__":
    print("🤖 AI Agent is ready! (Type 'exit' to stop)")
    print("-" * 50)
    
    while True:
        user_q = input("You: ")
        if user_q.lower() == 'exit':
            break
        
        print("Thinking...")
        
        # 1. Get Response from Gemini
        generated_response = get_gemini_response(user_q)
        
        # 2. Check for Guardrail (NO_SQL)
        if generated_response == "NO_SQL":
            print("\n🚫 ACCESS DENIED: I can only answer questions about the uploaded Database.")
            print("-" * 50)
        else:
            # It's valid SQL, so run it
            print(f"Start_SQL: {generated_response} :End_SQL") # Debugging
            
            result = execute_query(generated_response)
            
            print("\nResult:")
            print(result)
            print("-" * 50)